version: 2.1

jobs:
    deploy:
        docker:
            - image: cimg/base:stable
        steps:
            - run:
                name: Deploy Over SSH
                command: |
                    ssh $SSH_USER@$SSH_HOST "echo Hello-world"

workflows:
    only-deploy:
        jobs:
            - deploy:
                    filters:
                        branches:
                            only: main # only deploy on the main branch
