version: 2.1

jobs:
  deploy:
    docker:
      - image: alpine:3.15

    steps:
      - checkout
      - add_ssh_keys
      - run:
          name: "deploy Over SSH"
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "echo done"

workflows:
  build-and-deploy:
    jobs:
      - deploy
