version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable

    steps:
      - add_ssh_keys
      - run:
          name: "deploy Over SSH"
          command: |
            ls -lha
            ssh -o StrictHostKeyChecking=no emadu@$178.62.94.228 'ls'

workflows:
  build-and-deploy:
    jobs:
      - deploy
